/**
 * Curated skill collections — pre-assembled packs for common roles and workflows.
 *
 * Each collection defines a human-readable name, a description, an icon, and
 * an ordered list of skill IDs. The IDs must match those found in the skills
 * index (assets/skills_index.json).
 */

export interface SkillCollection {
  id: string;
  name: string;
  description: string;
  icon: string;           // VS Code ThemeIcon id
  skillIds: string[];
}

export const SKILL_COLLECTIONS: SkillCollection[] = [
  {
    id: 'essential-starter',
    name: 'Essential Starter',
    description: 'The must-have skills every developer should install first.',
    icon: 'star-full',
    skillIds: [
      'ai-engineer',
      'architect-review',
      'api-design-principles',
      'app-builder',
      'code-reviewer',
      'systematic-debugging',
      'git-pr-workflows-pr-enhance',
    ],
  },
  {
    id: 'fullstack-engineer',
    name: 'Full-Stack Engineer',
    description: 'End-to-end web development — frontend, backend, API, auth, and deployment.',
    icon: 'layers',
    skillIds: [
      'api-design-principles',
      'api-patterns',
      'architecture-patterns',
      'auth-implementation-patterns',
      'backend-dev-guidelines',
      'frontend-dev-guidelines',
      'nextjs-best-practices',
      'react-patterns',
      'react-state-management',
      'postgres-best-practices',
      'app-builder',
    ],
  },
  {
    id: 'ai-ml-specialist',
    name: 'AI / ML Specialist',
    description: 'Build AI agents, LLM integrations, RAG systems, and multi-agent workflows.',
    icon: 'hubot',
    skillIds: [
      'ai-engineer',
      'ai-agents-architect',
      'ai-agent-development',
      'ai-ml',
      'agent-orchestration-multi-agent-optimize',
      'autonomous-agent-patterns',
      'agent-memory-systems',
      'rag-engineer',
      'rag-implementation',
      'llm-app-patterns',
      'prompt-engineering-patterns',
      'vector-database-engineer',
      'mcp-builder',
      'langchain-architecture',
      'evaluation',
    ],
  },
  {
    id: 'security-auditor',
    name: 'Security Auditor',
    description: 'Comprehensive security testing, pen-testing, and code hardening skills.',
    icon: 'shield',
    skillIds: [
      'security-auditor',
      'api-security-best-practices',
      'api-security-testing',
      'threat-modeling-expert',
      'vulnerability-scanner',
      'web-security-testing',
      'pentest-checklist',
      'red-team-tactics',
      'sast-configuration',
      'backend-security-coder',
      'frontend-security-coder',
      'incident-response-incident-response',
    ],
  },
  {
    id: 'frontend-expert',
    name: 'Frontend Expert',
    description: 'React, Angular, Next.js, accessibility, performance, and UI systems.',
    icon: 'browser',
    skillIds: [
      'react-patterns',
      'react-state-management',
      'react-ui-patterns',
      'nextjs-app-router-patterns',
      'nextjs-best-practices',
      'angular',
      'angular-best-practices',
      'angular-state-management',
      'tailwind-design-system',
      'ui-ux-pro-max',
      'web-performance-optimization',
      'accessibility-compliance-accessibility-audit',
      'wcag-audit-patterns',
    ],
  },
  {
    id: 'backend-engineer',
    name: 'Backend Engineer',
    description: 'Node.js, Python, database, API, and server-side architecture skills.',
    icon: 'server',
    skillIds: [
      'backend-dev-guidelines',
      'architecture-patterns',
      'nodejs-backend-patterns',
      'fastapi-pro',
      'python-pro',
      'nestjs-expert',
      'postgres-best-practices',
      'sql-optimization-patterns',
      'database-architect',
      'api-design-principles',
      'auth-implementation-patterns',
      'microservices-patterns',
      'bun-development',
    ],
  },
  {
    id: 'devops-cloud',
    name: 'DevOps & Cloud',
    description: 'CI/CD, Kubernetes, Terraform, observability, and cloud deployment.',
    icon: 'cloud',
    skillIds: [
      'aws-skills',
      'aws-serverless',
      'terraform-infrastructure',
      'kubernetes-deployment',
      'kubernetes-architect',
      'docker-expert',
      'github-actions-templates',
      'cicd-automation-workflow-automate',
      'observability-monitoring-monitor-setup',
      'grafana-dashboards',
      'prometheus-configuration',
      'incident-responder',
      'deployment-procedures',
    ],
  },
  {
    id: 'data-engineer',
    name: 'Data Engineer',
    description: 'Data pipelines, analytics, SQL, ETL, Spark, and ML ops.',
    icon: 'graph',
    skillIds: [
      'data-engineering-data-pipeline',
      'dbt-transformation-patterns',
      'airflow-dag-patterns',
      'spark-optimization',
      'sql-pro',
      'sql-optimization-patterns',
      'database-design',
      'analytics-tracking',
      'data-quality-frameworks',
      'mlops-engineer',
      'data-storytelling',
    ],
  },
  {
    id: 'mobile-developer',
    name: 'Mobile Developer',
    description: 'iOS, Android, React Native, Flutter, and cross-platform app development.',
    icon: 'device-mobile',
    skillIds: [
      'react-native-architecture',
      'flutter-expert',
      'ios-developer',
      'android-jetpack-compose-expert',
      'swiftui-expert-skill',
      'kotlin-coroutines-expert',
      'expo-deployment',
      'mobile-design',
      'mobile-developer',
    ],
  },
  {
    id: 'testing-qa',
    name: 'Testing & QA',
    description: 'TDD, unit tests, e2e testing, test generation, and CI test automation.',
    icon: 'beaker',
    skillIds: [
      'tdd-workflow',
      'test-driven-development',
      'testing-patterns',
      'javascript-testing-patterns',
      'python-testing-patterns',
      'e2e-testing-patterns',
      'playwright-skill',
      'test-automator',
      'unit-testing-test-generate',
      'tdd-orchestrator',
      'webapp-testing',
    ],
  },
  {
    id: 'agentic-workflows',
    name: 'Agentic Workflows',
    description: 'Design and run multi-agent pipelines, memory, and orchestration.',
    icon: 'circuit-board',
    skillIds: [
      'ai-agents-architect',
      'multi-agent-patterns',
      'agent-orchestration-multi-agent-optimize',
      'dispatching-parallel-agents',
      'parallel-agents',
      'autonomous-agents',
      'agent-memory-systems',
      'agent-memory-mcp',
      'context-management-context-save',
      'context-management-context-restore',
      'context-window-management',
      'tool-design',
      'subagent-driven-development',
    ],
  },
  {
    id: 'startup-builder',
    name: 'Startup Builder',
    description: 'Launch fast — product, growth, analytics, payments, and automation.',
    icon: 'rocket',
    skillIds: [
      'app-builder',
      'ai-product',
      'startup-metrics-framework',
      'analytics-tracking',
      'ab-test-setup',
      'stripe-integration',
      'app-store-optimization',
      'seo-fundamentals',
      'marketing-psychology',
      'product-manager-toolkit',
      'marketing-ideas',
    ],
  },
  {
    id: 'architecture-patterns',
    name: 'Software Architecture',
    description: 'Clean architecture, DDD, event sourcing, microservices, and system design.',
    icon: 'symbol-class',
    skillIds: [
      'architect-review',
      'architecture-decision-records',
      'software-architecture',
      'domain-driven-design',
      'ddd-strategic-design',
      'ddd-tactical-patterns',
      'microservices-patterns',
      'event-sourcing-architect',
      'cqrs-implementation',
      'saga-orchestration',
      'api-design-principles',
      'monorepo-architect',
      'legacy-modernizer',
    ],
  },
  {
    id: 'automation-integrations',
    name: 'Automation & Integrations',
    description: 'Connect tools, automate workflows, and integrate SaaS services.',
    icon: 'zap',
    skillIds: [
      'n8n-mcp-tools-expert',
      'zapier-make-patterns',
      'workflow-automation',
      'github-automation',
      'slack-automation',
      'stripe-automation',
      'notion-automation',
      'jira-automation',
      'gmail-automation',
      'google-calendar-automation',
      'telegram-bot-builder',
      'discord-automation',
    ],
  },
  {
    id: 'azure-developer',
    name: 'Azure Developer',
    description: 'Azure services, AI, storage, identity, and cloud-native .NET development.',
    icon: 'cloud',
    skillIds: [
      'azure-ai-projects-py',
      'azure-ai-projects-ts',
      'azure-ai-agents-persistent-dotnet',
      'azure-functions',
      'azure-cosmos-py',
      'azure-storage-blob-ts',
      'azure-servicebus-ts',
      'azure-identity-py',
      'azure-keyvault-py',
      'azd-deployment',
      'azure-monitor-opentelemetry-py',
      'dotnet-architect',
    ],
  },
  {
    id: 'python-developer',
    name: 'Python Developer',
    description: 'Modern Python — FastAPI, async, testing, packaging, and performance.',
    icon: 'symbol-misc',
    skillIds: [
      'python-pro',
      'python-patterns',
      'fastapi-pro',
      'async-python-patterns',
      'python-testing-patterns',
      'python-performance-optimization',
      'python-packaging',
      'pydantic-models-py',
      'uv-package-manager',
      'django-pro',
    ],
  },
];

